# Environment Configuration
IS_REMOTE=false
DEVICE_TYPE=ANDROID
SERVER_URL=http://127.0.0.1:4723
ENV=local

# Android Capabilities
android.platform.name=Android
android.automation.name=UiAutomator2
android.device.name=Pixel_6_Pro_API_34
android.app.package=com.google.android.youtube
android.app.activity=com.google.android.youtube.HomeActivity

# iOS Capabilities
ios.platform.name=iOS
ios.automation.name=XCuiTest
ios.device.name=iPhone 14
ios.app.path=/apps/SauceLabs-Demo-App.Simulator.zip

# Common Appium Capabilities
appium.new.command.timeout=60
appium.full.reset=false
appium.no.reset=true

# Wait Configuration
wait.default.timeout=30
wait.default.polling=500
wait.driver.readiness.timeout=10
wait.driver.readiness.polling=500
wait.element.visibility.timeout=15
wait.element.clickability.timeout=15

# Remote Testing Configuration (BrowserStack, SauceLabs, etc.)
#SERVER_URL=https://hub.browserstack.com
